import { CompanyData } from '@/types/company';

export const DUMMY_COMPANIES: Record<string, CompanyData> = {
  AAPL: {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'NASDAQ',
    sector: 'Technology',
    price: '$214.52',
    numericPrice: 214.52,
    predictedPostEarningsPrice: '$228.10',
    numericPredictedPostEarningsPrice: 228.10,
    change: '+$5.08',
    changePercent: '+2.42%',
    isUp: true,
    marketCap: '$3.28T',
    high52: '$223.10',
    low52: '$169.20',
    revenue: '₹2.31T',
    eps: '23.14',
    predictionConfidence: '94%',
    aiInsights: {
      summary: 'Apple is experiencing strong upward momentum driven by services revenue acceleration and high consumer retention ahead of the upcoming M4 Mac and iPhone AI feature rollouts.',
      cautionLevel: 'Low Caution',
      cautionReason: 'Geopolitical supply chain concentration in East Asian assembly hubs remains a minor variable, though gross margin buffers are exceptionally robust.',
      pastEarningsSummary: 'In the previous earnings call, management exceeded revenue estimates by $1.8B. Services hit an all-time high of $24.2B with 14% growth. Executive tone was highly bullish on local neural engine execution.',
      nextEarningsOutlook: 'The upcoming earnings call is projected to showcase initial AI subscription monetization and holiday quarter channel inventory guidance. Analysts anticipate mid-single digit iPhone growth.',
      nextEarningsDate: 'Oct 31, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 209.50, predictedPrice: 209.80, confidenceUpper: 211.20, confidenceLower: 208.40 },
      { date: '10:30', time: '10:30 AM', actualPrice: 211.20, predictedPrice: 211.00, confidenceUpper: 212.80, confidenceLower: 209.60 },
      { date: '11:30', time: '11:30 AM', actualPrice: 210.80, predictedPrice: 211.50, confidenceUpper: 213.10, confidenceLower: 209.90 },
      { date: '12:30', time: '12:30 PM', actualPrice: 212.40, predictedPrice: 212.80, confidenceUpper: 214.50, confidenceLower: 211.10 },
      { date: '01:30', time: '01:30 PM', actualPrice: 213.10, predictedPrice: 213.60, confidenceUpper: 215.20, confidenceLower: 212.00 },
      { date: '02:30', time: '02:30 PM', actualPrice: 213.90, predictedPrice: 214.20, confidenceUpper: 216.00, confidenceLower: 212.40 },
      { date: '03:30', time: '03:30 PM', actualPrice: 214.52, predictedPrice: 215.00, confidenceUpper: 216.80, confidenceLower: 213.20 },
    ],
    news: [
      {
        id: 'aapl-1',
        headline: 'Apple expands AI investments across M4 chip lineup',
        description: 'Next-generation Silicon architecture optimizes local neural engine execution for enterprise workflows.',
        timeAgo: '2h ago',
      },
      {
        id: 'aapl-2',
        headline: 'Quarterly revenue exceeds institutional consensus',
        description: 'Services division revenue surges 14% year-over-year driven by App Store and subscriptions.',
        timeAgo: '5h ago',
      },
      {
        id: 'aapl-3',
        headline: 'New spatial computing SDK announced for developers',
        description: 'VisionOS updates introduce enterprise collaboration tools and expanded multi-monitor canvas support.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'aapl-4',
        headline: 'Supply chain optimization boosts gross margin target',
        description: 'Manufacturing diversification across Asian hubs improves operational resilience.',
        timeAgo: '2 days ago',
      },
      {
        id: 'aapl-5',
        headline: 'Analysts upgrade price target following iPhone supercycle signals',
        description: 'Wall Street firms highlight strong replacement demand across North America and Europe.',
        timeAgo: '3 days ago',
      },
    ],
  },

  RELIANCE: {
    ticker: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    exchange: 'NSE / BSE',
    sector: 'Energy & Conglomerate',
    price: '₹3,120.40',
    numericPrice: 3120.40,
    predictedPostEarningsPrice: '₹3,280.00',
    numericPredictedPostEarningsPrice: 3280.00,
    change: '+₹56.70',
    changePercent: '+1.85%',
    isUp: true,
    marketCap: '₹21.10T',
    high52: '₹3,217.00',
    low52: '₹2,220.50',
    revenue: '₹9.88T',
    eps: '104.20',
    predictionConfidence: '96%',
    aiInsights: {
      summary: 'Reliance continues solid expansion led by Jio 5G monetization and retail store network expansion, with clean energy infrastructure providing long-term structural tailwinds.',
      cautionLevel: 'Low Caution',
      cautionReason: 'Global refining margin fluctuations in the O2C division warrant routine monitoring, though offset by domestic retail demand strength.',
      pastEarningsSummary: 'Last quarter delivered EBITDA growth of 12% YoY. Jio subscriber revenue (ARPU) expanded to ₹181.7, while green energy capital expenditure was confirmed on target.',
      nextEarningsOutlook: 'Next earnings will focus on initial solar gigafactory commissioning updates and potential value unlocking timelines for the retail and digital business arms.',
      nextEarningsDate: 'Oct 21, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 3065.00, predictedPrice: 3070.00, confidenceUpper: 3090.00, confidenceLower: 3045.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 3080.00, predictedPrice: 3085.00, confidenceUpper: 3105.00, confidenceLower: 3060.00 },
      { date: '11:30', time: '11:30 AM', actualPrice: 3095.00, predictedPrice: 3100.00, confidenceUpper: 3120.00, confidenceLower: 3075.00 },
      { date: '12:30', time: '12:30 PM', actualPrice: 3105.00, predictedPrice: 3110.00, confidenceUpper: 3130.00, confidenceLower: 3085.00 },
      { date: '01:30', time: '01:30 PM', actualPrice: 3115.00, predictedPrice: 3118.00, confidenceUpper: 3140.00, confidenceLower: 3095.00 },
      { date: '02:30', time: '02:30 PM', actualPrice: 3118.00, predictedPrice: 3122.00, confidenceUpper: 3145.00, confidenceLower: 3100.00 },
      { date: '03:30', time: '03:30 PM', actualPrice: 3120.40, predictedPrice: 3125.00, confidenceUpper: 3150.00, confidenceLower: 3102.00 },
    ],
    news: [
      {
        id: 'rel-1',
        headline: 'Reliance Retail expands 5G integrated distribution hubs',
        description: 'Omnichannel logistics network cuts delivery timeframes by 40% in tier-1 metro corridors.',
        timeAgo: '1h ago',
      },
      {
        id: 'rel-2',
        headline: 'Green Energy Gigafactory construction hits milestone ahead of schedule',
        description: 'Solar module production capacity targets 20GW scaling by Q4 fiscal year.',
        timeAgo: '4h ago',
      },
      {
        id: 'rel-3',
        headline: 'Jio Platforms reports record ARPU expansion',
        description: 'Subscribers upgrading to unlimited 5G plans boost telecom segment operating margins.',
        timeAgo: '1 day ago',
      },
      {
        id: 'rel-4',
        headline: 'Oil-to-Chemicals segment stabilizes amid international crude recovery',
        description: 'High refining margins cushion energy revenue stream during global inventory shifts.',
        timeAgo: '2 days ago',
      },
      {
        id: 'rel-5',
        headline: 'Strategic partnership signed for hydrogen electrolyzer tech',
        description: 'Joint venture accelerates clean fuel transition across domestic industrial hubs.',
        timeAgo: '4 days ago',
      },
    ],
  },

  TCS: {
    ticker: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: 'NSE / BSE',
    sector: 'Technology Services',
    price: '₹4,320.15',
    numericPrice: 4320.15,
    predictedPostEarningsPrice: '₹4,210.00',
    numericPredictedPostEarningsPrice: 4210.00,
    change: '-₹28.30',
    changePercent: '-0.65%',
    isUp: false,
    marketCap: '₹15.60T',
    high52: '₹4,585.00',
    low52: '₹3,400.00',
    revenue: '₹2.40T',
    eps: '125.80',
    predictionConfidence: '92%',
    aiInsights: {
      summary: 'TCS is navigating a temporary pause in non-critical BFSI discretionary spend, though large-deal cloud transformation TCV remains resilient at $1.2B.',
      cautionLevel: 'Moderate Caution',
      cautionReason: 'Short-term margin headwinds due to wage revisions and delayed decision cycles in European regional markets require disciplined cost management.',
      pastEarningsSummary: 'Previous quarter reported constant currency growth of 4.4% YoY. Management highlighted strong order book conversion but noted extended sales cycles for new IT spending.',
      nextEarningsOutlook: 'Upcoming call expectations center on operating margin recovery back toward the 26% target band and deal intake execution across GenAI enterprise projects.',
      nextEarningsDate: 'Oct 15, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 4350.00, predictedPrice: 4345.00, confidenceUpper: 4370.00, confidenceLower: 4320.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 4340.00, predictedPrice: 4338.00, confidenceUpper: 4360.00, confidenceLower: 4315.00 },
      { date: '11:30', time: '11:30 AM', actualPrice: 4335.00, predictedPrice: 4330.00, confidenceUpper: 4355.00, confidenceLower: 4310.00 },
      { date: '12:30', time: '12:30 PM', actualPrice: 4328.00, predictedPrice: 4325.00, confidenceUpper: 4348.00, confidenceLower: 4302.00 },
      { date: '01:30', time: '01:30 PM', actualPrice: 4322.00, predictedPrice: 4320.00, confidenceUpper: 4340.00, confidenceLower: 4298.00 },
      { date: '02:30', time: '02:30 PM', actualPrice: 4325.00, predictedPrice: 4322.00, confidenceUpper: 4345.00, confidenceLower: 4300.00 },
      { date: '03:30', time: '03:30 PM', actualPrice: 4320.15, predictedPrice: 4318.00, confidenceUpper: 4340.00, confidenceLower: 4295.00 },
    ],
    news: [
      {
        id: 'tcs-1',
        headline: 'TCS secures $1.2B cloud modernization contract with European bank',
        description: 'Multi-year deal focuses on core banking cloud migration and generative AI integration.',
        timeAgo: '3h ago',
      },
      {
        id: 'tcs-2',
        headline: 'Employee attrition drops to lowest level in 12 quarters',
        description: 'Workforce retention strategies and upskilling initiatives yield positive operational metrics.',
        timeAgo: '6h ago',
      },
      {
        id: 'tcs-3',
        headline: 'AI cloud practice expands team to 100,000 certified engineers',
        description: 'Deep technical partnerships with AWS, Azure, and Google Cloud drive order pipeline.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'tcs-4',
        headline: 'UK insurance sector partnership renewed for 10-year term',
        description: 'Digital transformation framework streamlines claim processing times across 12 million policies.',
        timeAgo: '3 days ago',
      },
      {
        id: 'tcs-5',
        headline: 'TCS BaNCS platform adopted by top Latin American financial institution',
        description: 'SaaS deployment modernizes payment infrastructure across multi-country branch operations.',
        timeAgo: '5 days ago',
      },
    ],
  },

  INFY: {
    ticker: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE / NYSE',
    sector: 'Technology Services',
    price: '₹1,860.50',
    numericPrice: 1860.50,
    predictedPostEarningsPrice: '₹1,940.00',
    numericPredictedPostEarningsPrice: 1940.00,
    change: '+₹20.60',
    changePercent: '+1.12%',
    isUp: true,
    marketCap: '₹7.75T',
    high52: '₹1,980.00',
    low52: '₹1,350.00',
    revenue: '₹1.53T',
    eps: '62.40',
    predictionConfidence: '91%',
    aiInsights: {
      summary: 'Infosys is registering steady growth propelled by its Topaz AI platform adoption and large digital transformation contracts in manufacturing and retail.',
      cautionLevel: 'Low Caution',
      cautionReason: 'Pricing pressure on commoditized legacy maintenance contracts remains present, though offset by premium automation pricing.',
      pastEarningsSummary: 'In the prior earnings call, Infosys revised revenue guidance upward to 3.75%-4.5% in CC terms. Large deal TCV reached $3.4B with 52% net new deals.',
      nextEarningsOutlook: 'Next earnings will highlight initial revenue contributions from the NVIDIA AI factory partnership and FY27 annual guidance adjustments.',
      nextEarningsDate: 'Oct 17, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 1840.00, predictedPrice: 1842.00, confidenceUpper: 1855.00, confidenceLower: 1830.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 1848.00, predictedPrice: 1850.00, confidenceUpper: 1862.00, confidenceLower: 1838.00 },
      { date: '11:30', time: '11:30 AM', actualPrice: 1852.00, predictedPrice: 1855.00, confidenceUpper: 1868.00, confidenceLower: 1842.00 },
      { date: '12:30', time: '12:30 PM', actualPrice: 1855.00, predictedPrice: 1858.00, confidenceUpper: 1870.00, confidenceLower: 1845.00 },
      { date: '01:30', time: '01:30 PM', actualPrice: 1858.00, predictedPrice: 1860.00, confidenceUpper: 1872.00, confidenceLower: 1848.00 },
      { date: '02:30', time: '02:30 PM', actualPrice: 1860.00, predictedPrice: 1862.00, confidenceUpper: 1875.00, confidenceLower: 1850.00 },
      { date: '03:30', time: '03:30 PM', actualPrice: 1860.50, predictedPrice: 1864.00, confidenceUpper: 1878.00, confidenceLower: 1852.00 },
    ],
    news: [
      {
        id: 'infy-1',
        headline: 'Infosys Topaz AI platform delivers 30% productivity gain for telecom client',
        description: 'Generative AI assistant automates network diagnostic workflows and customer ticket routing.',
        timeAgo: '2h ago',
      },
      {
        id: 'infy-2',
        headline: 'Large deal TCV touches $3.4B in Q2 earnings release',
        description: 'North American banking and retail verticals rebound with strong discretionary spending.',
        timeAgo: '5h ago',
      },
      {
        id: 'infy-3',
        headline: 'Strategic collaboration announced with NVIDIA for enterprise LLM hosting',
        description: 'Custom AI factory solutions enable secure, domain-specific AI deployment for Fortune 500 firms.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'infy-4',
        headline: 'Nordics region revenue increases 18% YoY',
        description: 'Automotive and industrial manufacturing clients drive regional growth trajectory.',
        timeAgo: '3 days ago',
      },
      {
        id: 'infy-5',
        headline: 'Infosys Cobalt cloud suite wins global enterprise architecture award',
        description: 'Recognition highlights hybrid multi-cloud orchestration and security compliance tooling.',
        timeAgo: '4 days ago',
      },
    ],
  },

  MSFT: {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    sector: 'Technology',
    price: '$448.90',
    numericPrice: 448.90,
    predictedPostEarningsPrice: '$472.50',
    numericPredictedPostEarningsPrice: 472.50,
    change: '+$7.72',
    changePercent: '+1.75%',
    isUp: true,
    marketCap: '$3.34T',
    high52: '$468.35',
    low52: '$327.20',
    revenue: '$245.1B',
    eps: '11.80',
    predictionConfidence: '95%',
    aiInsights: {
      summary: 'Microsoft maintains dominant enterprise cloud leadership with Azure AI revenue accelerating 29% YoY and Copilot seats expanding across Fortune 500 deployments.',
      cautionLevel: 'Low Caution',
      cautionReason: 'Heavy AI data center capital expenditures ($19B/quarter) compress near-term free cash flow margins slightly, though backed by multi-year enterprise commitments.',
      pastEarningsSummary: 'Last earnings beat consensus EPS by $0.22. Intelligent Cloud revenue surged to $28.5B. Executive commentary emphasized capacity bottlenecks meeting AI demand.',
      nextEarningsOutlook: 'Upcoming call will provide key insights on Blackwell server availability, Azure capacity scaling, and commercial Copilot ARPU growth trajectories.',
      nextEarningsDate: 'Oct 29, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 441.20, predictedPrice: 442.00, confidenceUpper: 445.00, confidenceLower: 438.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 443.50, predictedPrice: 444.20, confidenceUpper: 447.50, confidenceLower: 440.00 },
      { date: '11:30', time: '11:30 AM', actualPrice: 445.00, predictedPrice: 445.80, confidenceUpper: 449.00, confidenceLower: 442.00 },
      { date: '12:30', time: '12:30 PM', actualPrice: 446.80, predictedPrice: 447.20, confidenceUpper: 450.50, confidenceLower: 443.50 },
      { date: '01:30', time: '01:30 PM', actualPrice: 447.50, predictedPrice: 448.00, confidenceUpper: 451.20, confidenceLower: 444.80 },
      { date: '02:30', time: '02:30 PM', actualPrice: 448.20, predictedPrice: 448.60, confidenceUpper: 452.00, confidenceLower: 445.20 },
      { date: '03:30', time: '03:30 PM', actualPrice: 448.90, predictedPrice: 449.50, confidenceUpper: 453.00, confidenceLower: 446.00 },
    ],
    news: [
      {
        id: 'msft-1',
        headline: 'Azure Cloud revenue grows 29% driven by enterprise AI adoption',
        description: 'Copilot integrations across Microsoft 365 suite record 60% quarter-over-quarter seats expansion.',
        timeAgo: '1h ago',
      },
      {
        id: 'msft-2',
        headline: 'Next-gen AI data center campus unveiled in Wisconsin',
        description: '$3.3B infrastructure commitment scales regional high-performance compute clusters.',
        timeAgo: '4h ago',
      },
      {
        id: 'msft-3',
        headline: 'Cybersecurity division surpasses $25B annual recurring revenue',
        description: 'Security Copilot and Defender tools mitigate multi-vector enterprise threats automatically.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'msft-4',
        headline: 'Gaming division revenues jump following Activision Blizzard integration',
        description: 'Game Pass subscriber numbers reach new peak across PC and console ecosystems.',
        timeAgo: '2 days ago',
      },
      {
        id: 'msft-5',
        headline: 'OpenAI partnership strengthened with dedicated supercomputing infrastructure',
        description: 'Custom silicon developments reduce inference latency for frontier AI models.',
        timeAgo: '3 days ago',
      },
    ],
  },

  TSLA: {
    ticker: 'TSLA',
    name: 'Tesla, Inc.',
    exchange: 'NASDAQ',
    sector: 'Automotive & Energy',
    price: '$254.20',
    numericPrice: 254.20,
    predictedPostEarningsPrice: '$238.00',
    numericPredictedPostEarningsPrice: 238.00,
    change: '-$5.58',
    changePercent: '-2.15%',
    isUp: false,
    marketCap: '$809.5B',
    high52: '$271.00',
    low52: '$138.80',
    revenue: '$96.8B',
    eps: '3.12',
    predictionConfidence: '88%',
    aiInsights: {
      summary: 'Tesla is transitioning from volume automotive growth to autonomous AI software (FSD v12), Megapack energy storage expansion, and next-gen Robotaxi manufacturing.',
      cautionLevel: 'High Caution',
      cautionReason: 'Automotive gross margin compression from global EV price reductions and regulatory timeline uncertainties for unsupervised FSD deployment necessitate close monitoring.',
      pastEarningsSummary: 'Previous earnings call missed automotive margin targets (14.6% vs 16.2% expected), though Energy Storage revenue grew 52% YoY to $3.0B.',
      nextEarningsOutlook: 'Upcoming earnings will reveal Cybercab launch milestones, Optimus V2 pilot operational feedback, and preliminary 2027 delivery volume guidance.',
      nextEarningsDate: 'Oct 23, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 260.00, predictedPrice: 259.00, confidenceUpper: 263.00, confidenceLower: 256.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 258.20, predictedPrice: 257.50, confidenceUpper: 261.00, confidenceLower: 254.00 },
      { date: '11:30', time: '11:30 AM', actualPrice: 256.50, predictedPrice: 256.00, confidenceUpper: 259.50, confidenceLower: 252.50 },
      { date: '12:30', time: '12:30 PM', actualPrice: 255.80, predictedPrice: 255.20, confidenceUpper: 258.80, confidenceLower: 251.80 },
      { date: '01:30', time: '01:30 PM', actualPrice: 254.90, predictedPrice: 254.50, confidenceUpper: 257.90, confidenceLower: 251.00 },
      { date: '02:30', time: '02:30 PM', actualPrice: 253.80, predictedPrice: 254.00, confidenceUpper: 257.00, confidenceLower: 250.00 },
      { date: '03:30', time: '03:30 PM', actualPrice: 254.20, predictedPrice: 254.50, confidenceUpper: 257.50, confidenceLower: 250.80 },
    ],
    news: [
      {
        id: 'tsla-1',
        headline: 'Robotaxi autonomous fleet testing milestone reached in Austin',
        description: 'Full Self-Driving v12 architecture logs over 1 billion unassisted vehicle miles.',
        timeAgo: '2h ago',
      },
      {
        id: 'tsla-2',
        headline: 'Megapack energy storage deployments surge 125% in Q3',
        description: 'Utility-scale battery installations drive record non-automotive gross margins.',
        timeAgo: '5h ago',
      },
      {
        id: 'tsla-3',
        headline: 'Cybercab production line tooling installed at Gigafactory Texas',
        description: 'Unboxed manufacturing method aims to lower vehicle assembly costs by up to 50%.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'tsla-4',
        headline: 'European Supercharger network opened to all EV brands',
        description: 'Infrastructure monetization strategy boosts recurring services revenue.',
        timeAgo: '2 days ago',
      },
      {
        id: 'tsla-5',
        headline: 'Optimus humanoid robot V2 begins pilot tasks in factory logistics',
        description: 'Autonomous spatial navigation and dexterity updates demonstrated in internal trials.',
        timeAgo: '4 days ago',
      },
    ],
  },

  NVDA: {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    sector: 'Semiconductors & AI',
    price: '$128.50',
    numericPrice: 128.50,
    predictedPostEarningsPrice: '$142.00',
    numericPredictedPostEarningsPrice: 142.00,
    change: '+$4.76',
    changePercent: '+3.85%',
    isUp: true,
    marketCap: '$3.16T',
    high52: '$140.76',
    low52: '$45.90',
    revenue: '$96.3B',
    eps: '2.45',
    predictionConfidence: '97%',
    aiInsights: {
      summary: 'NVIDIA commands near-monopolistic leadership in AI compute infrastructure, with Blackwell GPU architecture scaling into full volume manufacturing across top cloud providers.',
      cautionLevel: 'Low Caution',
      cautionReason: 'High customer concentration among top 4 cloud hyperscalers requires watching for any long-term datacenter capex moderation.',
      pastEarningsSummary: 'Prior earnings call reported extraordinary $30.0B in revenue (up 122% YoY). Data center segment generated $26.3B alone with 75.4% gross margins.',
      nextEarningsOutlook: 'Upcoming report is anticipated to confirm initial Blackwell shipments, spectrum-X networking adoption, and sovereign AI compute investments.',
      nextEarningsDate: 'Nov 20, 2026',
    },
    graphData: [
      { date: '09:30', time: '09:30 AM', actualPrice: 123.80, predictedPrice: 124.50, confidenceUpper: 126.00, confidenceLower: 122.00 },
      { date: '10:30', time: '10:30 AM', actualPrice: 125.20, predictedPrice: 125.80, confidenceUpper: 127.50, confidenceLower: 123.50 },
      { date: '11:30', time: '11:30 AM', actualPrice: 126.40, predictedPrice: 126.90, confidenceUpper: 128.80, confidenceLower: 124.80 },
      { date: '12:30', time: '12:30 PM', actualPrice: 127.10, predictedPrice: 127.60, confidenceUpper: 129.50, confidenceLower: 125.50 },
      { date: '01:30', time: '01:30 PM', actualPrice: 127.80, predictedPrice: 128.20, confidenceUpper: 130.10, confidenceLower: 126.20 },
      { date: '02:30', time: '02:30 PM', actualPrice: 128.10, predictedPrice: 128.50, confidenceUpper: 130.60, confidenceLower: 126.60 },
      { date: '03:30', time: '03:30 PM', actualPrice: 128.50, predictedPrice: 129.00, confidenceUpper: 131.20, confidenceLower: 127.00 },
    ],
    news: [
      {
        id: 'nvda-1',
        headline: 'Blackwell GPU architecture enters full volume production',
        description: 'Hyperscale cloud providers reserve initial 12-month manufacturing capacity for AI clusters.',
        timeAgo: '1h ago',
      },
      {
        id: 'nvda-2',
        headline: 'Data center quarterly revenue reaches historic $26B milestone',
        description: 'Demand for H200 and Spectrum-X networking switches accelerates sovereign AI deployments.',
        timeAgo: '3h ago',
      },
      {
        id: 'nvda-3',
        headline: 'NVIDIA Omniverse enterprise software stack adopts OpenUSD standard',
        description: 'Industrial digital twin platform adopted by top global aerospace and robotics leaders.',
        timeAgo: 'Yesterday',
      },
      {
        id: 'nvda-4',
        headline: 'DGX Cloud service expands availability across global telecom partners',
        description: 'Turnkey AI supercomputing infrastructure enables rapid enterprise model fine-tuning.',
        timeAgo: '2 days ago',
      },
      {
        id: 'nvda-5',
        headline: 'AUTOMOTIVE DRIVE Thor platform selected by next-gen EV manufacturers',
        description: 'Centralized computer architecture powers cockpit infotainment and autonomous driving stack.',
        timeAgo: '4 days ago',
      },
    ],
  },
};

export function getCompanyByTicker(query: string): CompanyData | null {
  if (!query) return null;
  const cleanQuery = query.trim().toUpperCase();
  return DUMMY_COMPANIES[cleanQuery] || null;
}
